// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Bun & Run_New

#include "ui.h"
#include "ui_helpers.h"

int dine[] = {0, 0, 0};
int takeaway[] = {0, 0, 0};
int GalBanis = 40;
int CreamBun = 60;
int FishBun = 80;


///////////////////// VARIABLES ////////////////////

void updateQr() {
    char qr_data[128];  // Increase size if needed based on your data length
    
    // Construct QR data string with values from dine array
    snprintf(qr_data, sizeof(qr_data), "example.com?dine={%d,%d,%d}&take={%d,%d,%d}", dine[0], dine[1], dine[2],takeaway[0],takeaway[1],takeaway[2]);
    
    // Create or update the QR code
    lv_obj_t *ui_qrcode = lv_qrcode_create(ui_Screen4, 100, lv_color_black(), lv_color_white());
    lv_qrcode_update(ui_qrcode, qr_data, strlen(qr_data));
    
    // Center the QR code on the screen
    lv_obj_center(ui_qrcode);
}

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label5;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label6;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Dropdown3;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Dropdown2;
lv_obj_t * ui_Dropdown4;
lv_obj_t * ui_Dropdown5;
lv_obj_t * ui_Dropdown6;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Container6;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    //#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void update_labels2() {
    char str[1000];
    
    // Update Label23: dine[1] + takeaway[1]
    snprintf(str, sizeof(str), "%d", dine[1] + takeaway[1]);
    lv_label_set_text(ui_Label23, str);
    
    // Update Label24: dine[0] + takeaway[0]
    snprintf(str, sizeof(str), "%d", dine[0] + takeaway[0]);
    lv_label_set_text(ui_Label24, str);
    
    // Update Label25: dine[2] + takeaway[2]
    snprintf(str, sizeof(str), "%d", dine[2] + takeaway[2]);
    lv_label_set_text(ui_Label25, str);
    
    // Update Label27: dine[1] + takeaway[1] * 40
    snprintf(str, sizeof(str), "%d", (dine[1] + takeaway[1]) * CreamBun);
    lv_label_set_text(ui_Label28, str);
    
    // Update Label28: dine[0] + takeaway[0] * 30
    snprintf(str, sizeof(str), "%d", (dine[0] + takeaway[0]) * GalBanis);
    lv_label_set_text(ui_Label27, str);
    
    // Update Label26: dine[2] + takeaway[2] * 80
    snprintf(str, sizeof(str), "%d", (dine[2] + takeaway[2]) * FishBun);
    lv_label_set_text(ui_Label26, str);
    
    // Update Label30: Sum of all previous calculations
    int total = ((dine[0] + takeaway[0] )* GalBanis )+ ((dine[1] + takeaway[1]) * CreamBun) + ((dine[2] + takeaway[2]) * FishBun);
    snprintf(str, sizeof(str), "%d", total);
    lv_label_set_text(ui_Label30, str);
}


void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(((dine[0] + takeaway[0] )* 30 )+ ((dine[1] + takeaway[1]) * 40) + ((dine[2] + takeaway[2]) * 80)==0){
        ;
    }else{
        if(event_code == LV_EVENT_CLICKED) {
            _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
        }
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_scr_load(ui_Screen2);
    }
}



///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
void ui_init2(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen5);
}
void updatePrice(){
    lv_label_set_text_fmt(ui_Label10, "Gal Banis(Rs.%d)",GalBanis);
    lv_label_set_text_fmt(ui_Label2, "Cream Bun(Rs.%d)",CreamBun);
    lv_label_set_text_fmt(ui_Label4, "Fish Bun(Rs.%d)",FishBun);
}

