// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Bun & Run_New

#ifndef _BUN_&_RUN_NEW_UI_H
#define _BUN_&_RUN_NEW_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include <src/extra/libs/qrcode/lv_qrcode.h>

    extern int dine[];
    extern int takeaway[];

    extern int GalBanis ;
    extern int CreamBun ;
    extern int FishBun ;



    // SCREEN: ui_Screen1
    void ui_Screen1_screen_init(void);
    extern lv_obj_t *ui_Screen1;
    extern lv_obj_t *ui_Container1;
    extern lv_obj_t *ui_Label2;
    extern lv_obj_t *ui_Label5;
    void ui_event_Button1(lv_event_t *e);
    extern lv_obj_t *ui_Button1;
    extern lv_obj_t *ui_Label6;
    // SCREEN: ui_Screen2
    void dropdown_event_handler(lv_event_t *e);
    void ui_Screen2_screen_init(void);
    extern lv_obj_t *ui_Screen2;
    extern lv_obj_t *ui_Container2;
    extern lv_obj_t *ui_Label7;
    extern lv_obj_t *ui_Label8;
    extern lv_obj_t *ui_Label9;
    extern lv_obj_t *ui_Label1;
    extern lv_obj_t *ui_Label3;
    extern lv_obj_t *ui_Label10;
    extern lv_obj_t *ui_Label4;
    extern lv_obj_t *ui_Label11;
    extern lv_obj_t *ui_Dropdown3;
    extern lv_obj_t *ui_Dropdown1;
    extern lv_obj_t *ui_Dropdown2;
    extern lv_obj_t *ui_Dropdown4;
    extern lv_obj_t *ui_Dropdown5;
    extern lv_obj_t *ui_Dropdown6;
    void ui_event_Button2(lv_event_t *e);
    extern lv_obj_t *ui_Button2;
    extern lv_obj_t *ui_Panel1;
    extern lv_obj_t *ui_Panel2;
    extern lv_obj_t *ui_Label12;
    extern lv_obj_t *ui_Label13;
    extern lv_obj_t *ui_Label14;
    // SCREEN: ui_Screen3
    void ui_Screen3_screen_init(void);
    extern lv_obj_t *ui_Screen3;
    extern lv_obj_t *ui_Container3;
    extern lv_obj_t *ui_Label15;
    extern lv_obj_t *ui_Label16;
    extern lv_obj_t *ui_Label17;
    extern lv_obj_t *ui_Panel4;
    extern lv_obj_t *ui_Label18;
    extern lv_obj_t *ui_Label19;
    extern lv_obj_t *ui_Panel3;
    extern lv_obj_t *ui_Label20;
    extern lv_obj_t *ui_Label21;
    extern lv_obj_t *ui_Label22;
    extern lv_obj_t *ui_Label23;
    extern lv_obj_t *ui_Label24;
    extern lv_obj_t *ui_Label25;
    extern lv_obj_t *ui_Label26;
    extern lv_obj_t *ui_Label27;
    extern lv_obj_t *ui_Label28;
    extern lv_obj_t *ui_Panel5;
    extern lv_obj_t *ui_Label29;
    extern lv_obj_t *ui_Label30;
    void ui_event_Button4(lv_event_t *e);
    extern lv_obj_t *ui_Button4;
    void ui_event_Button3(lv_event_t *e);
    extern lv_obj_t *ui_Button3;
    extern lv_obj_t *ui_Label31;
    extern lv_obj_t *ui_Label32;
    extern lv_obj_t *ui_Panel6;
    extern lv_obj_t *ui_Panel7;
    // SCREEN: ui_Screen4
    void ui_Screen4_screen_init(void);
    extern lv_obj_t *ui_Screen4;
    extern lv_obj_t *ui_Container6;
    // SCREEN: ui_Screen5
    void ui_Screen5_screen_init(void);
    extern lv_obj_t *ui_Screen5;
    extern lv_obj_t *ui_Container7;
    extern lv_obj_t *ui_Label33;
    extern lv_obj_t *ui_Label34;
    extern lv_obj_t *ui____initial_actions0;

    LV_FONT_DECLARE(ui_font_Font1);
    LV_FONT_DECLARE(ui_font_Font2);
    LV_FONT_DECLARE(ui_font_Font3);
    LV_FONT_DECLARE(ui_font_Font4);

    void ui_init(void);
    void ui_init2(void);
    void update_labels2();
    void updatePrice();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
